---
- name: Test hello world
  hosts: all
  tasks: 
  - name: Create a snapshot
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      folder: "/{{ datacenter_folder }}"
      name: "{{ guest_name }}"
      state: present
      snapshot_name: "{{ snapshot_name }}"
      description: "{{ snapshot_description }}"
    delegate_to: localhost